export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const UPDATE_PURCHASE_STATE = "UPDATE_PURCHASE_STATE";
export const INPUT_CHANGED = "INPUT_CHANGED";
